//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EventEnum.java
//  @ Date : 2015/5/5
//  @ Author : 
//
//


package org.lubei.bases.core.msg;


import java.io.Serializable;

/**
 * 消息中间件中事件基类,统一通过此类进行消息转发,本身提供序列化方法，实现消息传输过程中的序列化和反序列化
 *
 * @param <T> 消息实体数据类型,按照实体类型分发到不同得消息处理函数中
 */
public class MsgBaseEvent<T> implements Serializable {
    protected String type;
    protected T data;

    /**
     * 构造函数
     *
     * @param type : 生产者/消费者注册时，提供的消息类型
     * @param data : 消息实体数据
     */
    public MsgBaseEvent(String type, T data) {
        this.type = type;
        this.data = data;
    }

    /**
     * 消息注册类型(生产者/消费者注册时，提供的消息类型)
     *
     * @return
     */
    public String getType() {
        return type;
    }

    /**
     * 消息实体内容
     *
     * @return
     */
    public T getData() {
        return data;
    }
}
